version: "3.8"

services:
  sensor-filter:
    container_name: sensor-filter
    image: sensor-filter
    build:
      context: ./modules/sensor_filter
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      - DEV_IOTHUB_DEVICE_CONNECTION_STRING=change_me
      - TEMPERATURE_THRESHOLD=20
      - MESSAGE_INTERVAL=5
    volumes:
      - ./modules/sensor_filter:/opt
