name: Deploy Modules

on:
  workflow_dispatch:
    inputs:
      image_tag_version:
        description: Docker image tag version.
        required: true
        default: "1.0.0"

env:
  docker_hub_username: "${{ secrets.DOCKERHUB_USER }}"
  docker_hub_password: "${{ secrets.DOCKERHUB_TOKEN }}"

defaults:
  run:
    shell: bash
    working-directory: ./

jobs:
  build-and-push:
    name: Build and Push Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Action
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.docker_hub_username }}
          password: ${{ env.docker_hub_password }}

      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          context: ./modules/sensor_filter
          push: true
          platforms: linux/arm64
          tags: ${{ env.docker_hub_username }}/sensor-filter:${{ github.event.inputs.image_tag_version }}
