name: PR Linter

on: pull_request

jobs:
  run-linter:
    name: Run Linter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Action
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Lint Codebase
        uses: github/super-linter/slim@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: master
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_JSCPD: false
          VALIDATE_PYTHON_MYPY: false
          VALIDATE_GITHUB_ACTIONS: false
          VALIDATE_PYTHON_ISORT: false
          VALIDATE_NATURAL_LANGUAGE: false
          VALIDATE_YAML: false
          FILTER_REGEX_EXCLUDE: (README.md|.github/*)
          IGNORE_GITIGNORED_FILES: true
